server {
    listen 443 ssl;
    server_name 127.0.0.1 localhost;

    root /var/www/html/public;
    index index.php;

    ssl_certificate /etc/nginx/certs/localhost.crt;
    ssl_certificate_key /etc/nginx/certs/localhost.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    charset utf-8;
    client_max_body_size 6m;

    location / {
        try_files $uri $uri/ /index.php?s=$uri&$query_string;
    }

    location = /index.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/html/public;
        fastcgi_pass php:9000;
        fastcgi_read_timeout 60s;
    }

    location ~ /\. {
        deny all;
    }

    location ~ \.php$ {
        return 404;
    }
}
